---

- name: Install FreeIPA server packages
  package:
    name: "{{ freeipa_server_pkgs }}"
    state: present
    update_cache: "{{ omit if ansible_pkg_mgr == 'dnf' else 'yes' }}"

- name: Install FreeIPA client pip dependencies
  pip:
    name: "{{ freeipa_server_pip_pkgs }}"
    state: present
